include: package:very_good_analysis/analysis_options.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
    directives_ordering: ignore
    sort_pub_dependencies: ignore

linter:
  rules:
    public_member_api_docs: false
